### ISSUE TITLE
pandas not updated - concat() got an unexpected keyword argument 'join_axes'

### ISSUE THREAD

**Issue by kernb2** [raman-noodles/raman-spectra-decomp-analysis#52]
In peakidentify.py 

ERROR: This function tests the operation of the peak_assignment
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/raman-noodles/raman-spectra-decomp-analysis/ramandecompy/tests/test_peakidentify.py", line 42, in test_peak_assignment
    precision, False, plot = False)
  File "/home/travis/build/raman-noodles/raman-spectra-decomp-analysis/ramandecompy/peakidentify.py", line 157, in peak_assignment
    copy=True,sort=True)
TypeError: concat() got an unexpected keyword argument 'join_axes'

ERROR: Evaluates the functionality of the score_table function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/raman-noodles/raman-spectra-decomp-analysis/ramandecompy/tests/test_peakidentify.py", line 872, in test_score_table
    peakidentify.score_table(unknown_peaks,H2O_peaks, precision,unknownname,knownname)
  File "/home/travis/build/raman-noodles/raman-spectra-decomp-analysis/ramandecompy/peakidentify.py", line 752, in score_table
    copy=True,sort=True)
TypeError: concat() got an unexpected keyword argument 'join_axes'

Solution update pandas on travis

**Comment by erasmuss** [comment]
I looked this error up and it may be an update issue, see link: https://github.com/ShichenXie/scorecardpy/issues/2

**Comment by erasmuss** [comment]
https://pandas.pydata.org/pandas-docs/version/0.23.1/generated/pandas.concat.html

**Comment by erasmuss** [comment]
This was fixed by removing the join_axes from the concat function
