### ISSUE TITLE
Multiple file exists errors in test_dataprep.py & test_dataimport.py

### ISSUE THREAD

**Issue by kernb2** [raman-noodles/raman-spectra-decomp-analysis#54]
======================================================================
ERROR: This function tests the operation of the peak_assignment
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user1\Anaconda3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\user1\Desktop\raman-spectra-decomp-analysis\ramandecompy\tests\test_dataimport.py", line 16, in test_data_import
    dataprep.new_hdf5('exp_test_3')
  File "C:\Users\user1\Desktop\raman-spectra-decomp-analysis\ramandecompy\dataprep.py", line 36, in new_hdf5
    hdf5 = h5py.File('{}.hdf5'.format(new_filename), 'w-')
  File "C:\Users\user1\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "C:\Users\user1\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 174, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'exp_test_3.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = 502)

======================================================================
ERROR: A function that tests the `add_calibration` function from dataprep. It first tests that no
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user1\Anaconda3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\user1\Desktop\raman-spectra-decomp-analysis\ramandecompy\tests\test_dataprep.py", line 28, in test_add_calibration
    dataprep.new_hdf5('test')
  File "C:\Users\user1\Desktop\raman-spectra-decomp-analysis\ramandecompy\dataprep.py", line 36, in new_hdf5
    hdf5 = h5py.File('{}.hdf5'.format(new_filename), 'w-')
  File "C:\Users\user1\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "C:\Users\user1\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 174, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'test.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = 502)

======================================================================
ERROR: A function that tests the `add_experiment` function from dataprep. It first tests that no
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user1\Anaconda3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\user1\Desktop\raman-spectra-decomp-analysis\ramandecompy\tests\test_dataprep.py", line 73, in test_add_experiment
    dataprep.new_hdf5('exp_test_1')
  File "C:\Users\user1\Desktop\raman-spectra-decomp-analysis\ramandecompy\dataprep.py", line 36, in new_hdf5
    hdf5 = h5py.File('{}.hdf5'.format(new_filename), 'w-')
  File "C:\Users\user1\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "C:\Users\user1\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 174, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'exp_test_1.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = 502)

======================================================================
ERROR: A function that tests the `adjust_peaks` function from dataprep. The function first looks to
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user1\Anaconda3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\user1\Desktop\raman-spectra-decomp-analysis\ramandecompy\tests\test_dataprep.py", line 111, in test_adjust_peaks
    dataprep.new_hdf5('exp_test_2')
  File "C:\Users\user1\Desktop\raman-spectra-decomp-analysis\ramandecompy\dataprep.py", line 36, in new_hdf5
    hdf5 = h5py.File('{}.hdf5'.format(new_filename), 'w-')
  File "C:\Users\user1\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "C:\Users\user1\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 174, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'exp_test_2.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = 502)

Solution:
Make sure to hdf5.close() & os.remove() these files before or figure out why it doesnt work with Brandon's nosetests

**Comment by erasmuss** [comment]
So I found that this is more a limitation with hdf5 file types and thus the way the code is executed. 

link explaining: https://github.com/h5py/h5py/issues/1090

> Because that requires the hdf5-library to be built with parallel extensions. You can open an HDF5-file for read-only in multiple processes, but you cannot open it for read/write in more than one process unless the library has been built with parallel enabled.
> The reason for this is because HDF5-files write to the file the moment you close them, not the moment you tell them to write. Therefore, in serial, corruption would be very likely.
> 
> The best way to deal with this is by simply opening the HDF5-file for read-only in both Python scripts. That should work perfectly fine.

**Comment by erasmuss** [comment]
Also in the same link (https://github.com/h5py/h5py/issues/1090) it was mentioned that SWMR file types could be useful in future...

> You may also be interested in SWMR (if you only need to write from one process, but read from many).

http://docs.h5py.org/en/stable/swmr.html

**Comment by erasmuss** [comment]
https://github.com/h5py/h5py/issues/940

The above link goes into this in even more details

**Comment by erasmuss** [comment]
this bug has now been crushed
